name: Unit Tests
env:
  DATABASE_URL: ${{ secrets.STAGING_DATABASE_URL }}
  SUPERGOOD_CLIENT_ID: ${{ secrets.STAGING_SUPERGOOD_CLIENT_ID }}
  SUPERGOOD_CLIENT_SECRET: ${{ secrets.STAGING_SUPERGOOD_CLIENT_SECRET }}
  SUPERGOOD_BASE_URL: ${{ vars.SUPERGOOD_BASE_URL }}
  SUPERGOOD_ORGANIZATION_ID: ${{ vars.SUPERGOOD_ORGANIZATION_ID }}
on:
  push:
    branches:
      - master
  pull_request:
    branches: [master]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run Tests
        run: |
          bundle install --path .bundle
          bundle exec rspec spec/client_spec.rb
