name: Unit Tests
env:
  DATABASE_URL: ${{ secrets.STAGING_DATABASE_URL }}
  SUPERGOOD_CLIENT_ID: ${{ secrets.STAGING_SUPERGOOD_CLIENT_ID }}
  SUPERGOOD_CLIENT_SECRET: ${{ secrets.STAGING_SUPERGOOD_CLIENT_SECRET }}
  SUPERGOOD_BASE_URL: ${{ vars.SUPERGOOD_BASE_URL }}
  SUPERGOOD_ORGANIZATION_ID: ${{ vars.SUPERGOOD_ORGANIZATION_ID }}
on:
  push:
    branches:
      - master
  pull_request:
    branches: [master]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Ruby
        uses: ruby/setup-ruby@359bebbc29cbe6c87da6bc9ea3bc930432750108
        with:
          ruby-version: '3.2.1'
      - name: Install dependencies
        run: bundle install
      - name: Run tests
        run: bundle exec rspec spec/client_spec.rb
